name: checkbox-gfx
summary: Checkbox tests for testing graphics
description: |
  Collection of tests to be run on devices to test graphics functionality
version: '1.0'
confinement: classic
grade: stable

base: core24

# Here are the available applications of the graphics checkbox provider snap
# To run : snap run checkbox-gfx.<app>
#
# checkbox-cli:
#   - checkbox client, can be used to talk to the checkbox daemon
# configure:
#   - inject environment variable into checkbox snap environnement
#     the variable initial list can be found in config/config_vars
#     use configure -l to get the list of the current variables
#     For example, a useful use case is to inject environment variable
#     to enable debugging output (LIBVA_MESSAGING_LEVEL)
# remote-slave:
#   - checkbox slave daemon that will the responsible for running the test sesssion
#     in the remote fashion (through checkbox-cli)
# shell:
#   - give shell access to the provider snap
# install:
#   - install all depedencies needed for provider jobs
# test:
#   - Run the regression test suite
apps:
  checkbox-cli:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper
  configure:
    command-chain: [bin/wrapper_local]
    command: bin/configure
  test:
    command-chain: [bin/wrapper_local]
    command: bin/test
  test-lvl-zero:
    command-chain: [bin/wrapper_local]
    command: bin/test-lvl-zero
  test-lvl-zero-rt:
    command-chain: [bin/wrapper_local]
    command: bin/test-lvl-zero-rt
  remote-slave:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper slave
    daemon: simple
    restart-condition: always
  shell:
    command-chain: [bin/wrapper_local]
    command: bin/shell-wrapper
  install:
    command: bin/install
  remove:
    command: bin/remove

passthrough:
  hooks:
    configure:
      command-chain: [bin/wrapper_local]

parts:
  checkbox-provider-gfx:
    plugin: dump
    source: ./checkbox-provider-gfx
    source-type: local
    build-snaps:
      - checkbox-provider-tools
      - checkbox24
    stage-packages:
      - python3-tinydb
      - python3-filelock
      - intel-gpu-tools
  bin:
    plugin: dump
    source: bin/
    organize:
      '*': bin/
  config-variables:
    plugin: dump
    source: config/

