name: "Build Level Zero Raytracing - amd64"
on:
  push:
    branches:
      - test_gh_runner
  pull_request:
    branches:
      - main
    paths:
      - bin/install-lvl-zero-rt

jobs:
  run-install-lvl-zero-rt:
    name: "Run install-lvl-zero-rt to generate test binaries"
    runs-on: [ self-hosted, linux, "amd64", "noble" ]

    steps:
      - name: checkout the main repo
        uses: actions/checkout@v4

      - name: Run install-lvl-zero-rt
        shell: bash
        run: |
          bin/install-lvl-zero-rt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: |
            /usr/local/checkbox-gfx/*
