name: "Build OpenCL - ARM"
on:
  push:
    branches:
      - test_gh_runner
  pull_request:
    branches:
      - main
    paths:
      - bin/install-opencl

jobs:
  run-install-opencl:
    name: "Run install-opencl to generate test binaries"
    runs-on: [ self-hosted, linux, "arm64", "noble" ]

    steps:
      - name: checkout the main repo
        uses: actions/checkout@v4

      - name: Run install-opencl
        shell: bash
        run: |
          bin/install-opencl

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: |
            /usr/local/checkbox-gfx/*
