name: "Build Crucible - ARM"
on:
  push:
    branches:
      - test_gh_runner
  pull_request:
    branches:
      - main
    paths:
      - bin/install-crucible

jobs:
  run-install-crucible-arm:
    name: "Run install-crucible to generate Mesa testing binaries"
    runs-on: [ self-hosted, linux, "arm64", "noble" ]

    steps:
      - name: checkout the main repo
        uses: actions/checkout@v4

      - name: Run install-crucible
        shell: bash
        run: |
          bin/install-crucible

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: |
            /usr/local/checkbox-gfx/*
