name: Do a snap build and push to store

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md' # Don't trigger if doc updated
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md' # Don't trigger if doc updated
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
